# ansible/roles/base/tasks/main.yml
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade all packages
  apt:
    upgrade: dist

- name: Install common packages
  apt:
    name:
      - git
      - curl
      - vim
      - unzip
    state: present
