#!/usr/bin/env -S uv run --script

import typer
from commands import builder

app = typer.Typer(pretty_exceptions_enable=False)
app.command("run")(builder.playbook)
app.command("list")(builder.list_playbooks)

if __name__ == "__main__":
    app()