# ansible/roles/vscode/tasks/main.yml
- name: Add Microsoft GPG key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add VS Code repository
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
    state: present

- name: Install VS Code
  apt:
    name: code
    state: present
    update_cache: yes

- name: Install VS Code extensions
  command: "code --install-extension {{ item }}"
  with_items:
    - ms-python.python
    - HashiCorp.terraform
  become: no
  ignore_errors: yes
